[package]
name = "rs_algo_shared"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.56"
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_qs = "0.9.1"
bson = { version = "2.1.0", features = ["chrono-0_4"]} 
reqwest = { version = "0.11.9", features = ["json"] }
ta = {version = "0.5.0", features = ["serde"] }
chrono = {version = "0.4.19",  features = ["serde","wasmbind", "js-sys"]}
plotters = {git = "https://github.com/pmagaz/plotters", features = ["all_series"]}
